# Generated by Django 4.2.2 on 2024-06-03 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datea', models.DateTimeField(verbose_name='datea')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('email', models.CharField(max_length=75, verbose_name='email')),
                ('application_title', models.CharField(max_length=254, verbose_name='application_title')),
                ('application_details', models.TextField(verbose_name='application_details')),
                ('final', models.CharField(max_length=254, verbose_name='final')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total')),
            ],
            options={
                'db_table': 'view_application',
                'ordering': ['datea'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datea', models.DateTimeField(auto_now_add=True, verbose_name='datea')),
                ('application_title', models.CharField(max_length=256, verbose_name='application_title')),
                ('application_details', models.TextField(verbose_name='application_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application',
                'ordering': ['datea'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=128, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=256, verbose_name='service_title')),
                ('details', models.TextField(verbose_name='service_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='service_price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='service_photo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_category', to='agency.category')),
            ],
            options={
                'db_table': 'service',
                'ordering': ['service_title'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField(auto_now_add=True, verbose_name='dates')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='sale_payment')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_application', to='agency.application')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_application', to='agency.service')),
            ],
            options={
                'db_table': 'sale',
                'ordering': ['dates'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('news_title', models.CharField(max_length=256, verbose_name='news_title')),
                ('details', models.TextField(verbose_name='news_details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='news_photo')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
                'indexes': [models.Index(fields=['daten'], name='news_daten_a29edb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datem', models.DateTimeField(verbose_name='datem')),
                ('status', models.CharField(max_length=128, verbose_name='movement_status')),
                ('details', models.TextField(blank=True, null=True, verbose_name='movement_details')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_application', to='agency.application')),
            ],
            options={
                'db_table': 'movement',
                'ordering': ['datem'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'service_title'], name='service_categor_c73d06_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['application'], name='sale_applica_3e1f46_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['dates'], name='sale_dates_67c5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['application'], name='movement_applica_27871b_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['datem'], name='movement_datem_8708fe_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['datea'], name='application_datea_198fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='application_user_id_ba75f5_idx'),
        ),
    ]
